### ISSUE TITLE
Pre-Release Tasks: 4- Update page titles using React Helmet

### ISSUE THREAD

**Issue by emaDBytes** [unicornteam2024/quizzer#139]
Currently, all pages show "Vite + React" as the browser tab title. We need to implement dynamic page titles using React Helmet for better user experience and SEO.

## Tasks
1. Setup React Helmet
  - [ ] Run `npm install react-helmet` in student-dashboard directory
  - [ ] Verify installation in package.json

2. Update Page Components
  - [ ] Quiz List Page
    ```jsx
    <Helmet>
      <title>Available Quizzes - Quizzer</title>
      <meta name="description" content="Browse and take available quizzes" />
    </Helmet>
    ```
  - [ ] Quiz Details Page
    ```jsx
    <Helmet>
      <title>{`${quiz.title} - Quizzer`}</title>
      <meta name="description" content={quiz.description} />
    </Helmet>
    ```
  - [ ] Quiz Results Page
    ```jsx
    <Helmet>
      <title>{`Quiz Results: ${quiz.title} - Quizzer`}</title>
      <meta name="description" content={`Results for ${quiz.title}`} />
    </Helmet>
    ```
  - [ ] Categories Page
    ```jsx
    <Helmet>
      <title>Quiz Categories - Quizzer</title>
      <meta name="description" content="Browse quizzes by category" />
    </Helmet>
    ```
  - [ ] Reviews Page
    ```jsx
    <Helmet>
      <title>{`Reviews: ${quiz.title} - Quizzer`}</title>
      <meta name="description" content={`Student reviews for ${quiz.title}`} />
    </Helmet>
    ```

3. Testing
  - [ ] Verify titles update correctly when navigating between pages
  - [ ] Check that dynamic content (quiz titles, etc.) appears correctly
  - [ ] Test in different browsers

## Why
- Improves user experience by showing relevant page titles in browser tabs
- Enhances SEO with proper page titles and meta descriptions
- Follows professional web development best practices

## Implementation Notes
- Import needed in each page: `import { Helmet } from 'react-helmet'`
- Place Helmet component right after opening fragment in return statement
- Use consistent title format: `Specific Page Info - Quizzer`

## Labels
- enhancement
- frontend
- SEO

## Priority
Medium - Should be completed before final release
